#!/usr/bin/env bash
branch="${TRAVIS_PULL_REQUEST_BRANCH:-"${TRAVIS_BRANCH:-$(git symbolic-ref HEAD 2>/dev/null)}"}"
regex='(.*)(^|/)([A-Z]+[A-Z0-9]?-[0-9]+)(.*)'

CYPRESS_TAGS="@COMPLETED"

[[ $branch =~ $regex ]] && CYPRESS_TAGS="@${BASH_REMATCH[3]} or @COMPLETED"

export CYPRESS_TEST_LEVEL="${1:-ui}"

if [ "$CYPRESS_TEST_LEVEL" = "ui" ]; then
  export CYPRESS_TAGS="($CYPRESS_TAGS) and not @API"
fi

if [ "$CYPRESS_TEST_LEVEL" = "api" ]; then
  export CYPRESS_TAGS="($CYPRESS_TAGS) and not @UI"
fi

echo "Going to run cypress with the following tags: $CYPRESS_TAGS on $CYPRESS_TEST_LEVEL level"

cypress-tags run -e TAGS="$CYPRESS_TAGS"
